//! Compliance Report Generator — Markdown output
//!
//! Consolidates SAST, SCA, buddy status, and binary integrity.

use crate::security::{ScanReport, SecurityScanner, Severity};
use chrono::Local;
use sha2::{Sha256, Digest};
use std::path::Path;

/// Generate a full compliance report in Markdown
pub fn generate_report(
    project_name: &str,
    scan_reports: &[ScanReport],
    buddy_name: &str,
    buddy_level: u32,
    buddy_vulns_caught: u64,
    grimoire_patterns: usize,
    binary_path: Option<&Path>,
) -> String {
    let timestamp = Local::now().format("%Y-%m-%d %H:%M:%S").to_string();
    let total = SecurityScanner::total_findings(scan_reports);
    let (c, e, w, i) = SecurityScanner::severity_counts(scan_reports);

    let mut md = String::new();

    // Header
    md.push_str(&format!("# Security Compliance Report\n\n"));
    md.push_str(&format!("**Project:** {project_name}  \n"));
    md.push_str(&format!("**Generated:** {timestamp}  \n"));
    md.push_str(&format!("**Tool:** Sovereign v{}  \n\n", env!("CARGO_PKG_VERSION")));

    // Executive Summary
    md.push_str("## Executive Summary\n\n");
    md.push_str(&format!("| Metric | Value |\n|---|---|\n"));
    md.push_str(&format!("| Total Findings | {total} |\n"));
    md.push_str(&format!("| Critical | {c} |\n"));
    md.push_str(&format!("| Error | {e} |\n"));
    md.push_str(&format!("| Warning | {w} |\n"));
    md.push_str(&format!("| Info | {i} |\n"));
    md.push_str(&format!("| Grimoire Patterns | {grimoire_patterns} |\n\n"));

    let risk = if c > 0 { "HIGH" } else if e > 0 { "MEDIUM" } else if w > 0 { "LOW" } else { "CLEAN" };
    md.push_str(&format!("**Risk Level:** {risk}\n\n"));

    // SAST Results
    md.push_str("## SAST Results (Static Analysis)\n\n");
    let sast_reports: Vec<&ScanReport> = scan_reports.iter()
        .filter(|r| r.tool == "Semgrep" || r.tool == "clippy")
        .collect();

    if sast_reports.is_empty() {
        md.push_str("No SAST tools were executed.\n\n");
    } else {
        for report in &sast_reports {
            md.push_str(&format!("### {}\n\n", report.tool));
            if report.findings.is_empty() {
                md.push_str("No findings.\n\n");
            } else {
                md.push_str("| Severity | Rule | File | Line | Message |\n|---|---|---|---|---|\n");
                for f in &report.findings {
                    let line = f.line.map(|l| l.to_string()).unwrap_or_else(|| "-".into());
                    let owasp = f.owasp_category.as_deref().unwrap_or("");
                    md.push_str(&format!(
                        "| {} | {} {} | {} | {} | {} |\n",
                        f.severity, f.rule_id, owasp,
                        f.file.display(), line,
                        truncate(&f.message, 80),
                    ));
                }
                md.push('\n');
            }
        }
    }

    // SCA Results
    md.push_str("## SCA Results (Dependency Analysis)\n\n");
    let sca_reports: Vec<&ScanReport> = scan_reports.iter()
        .filter(|r| r.tool == "cargo-audit")
        .collect();

    if sca_reports.is_empty() {
        md.push_str("No SCA tools were executed.\n\n");
    } else {
        for report in &sca_reports {
            if report.findings.is_empty() {
                md.push_str("No vulnerable dependencies found.\n\n");
            } else {
                md.push_str("| Advisory | Severity | Description |\n|---|---|---|\n");
                for f in &report.findings {
                    md.push_str(&format!(
                        "| {} | {} | {} |\n",
                        f.rule_id, f.severity, truncate(&f.message, 100),
                    ));
                }
                md.push('\n');
            }
        }
    }

    // Familiar Status
    md.push_str("## Project Familiar Status\n\n");
    md.push_str(&format!("| Stat | Value |\n|---|---|\n"));
    md.push_str(&format!("| Name | {buddy_name} |\n"));
    md.push_str(&format!("| Level | {buddy_level} |\n"));
    md.push_str(&format!("| Vulnerabilities Caught | {buddy_vulns_caught} |\n\n"));

    // Binary Integrity
    md.push_str("## Binary Integrity\n\n");
    if let Some(path) = binary_path {
        if let Ok(hash) = compute_binary_hash(path) {
            md.push_str(&format!("**Binary:** `{}`  \n", path.display()));
            md.push_str(&format!("**SHA-256:** `{hash}`  \n\n"));
        } else {
            md.push_str("Binary hash computation failed.\n\n");
        }
    } else {
        md.push_str("No binary path provided.\n\n");
    }

    // Footer
    md.push_str("---\n\n");
    md.push_str(&format!("*Report generated by Sovereign v{}*\n", env!("CARGO_PKG_VERSION")));

    md
}

/// Compute SHA-256 of a binary file
fn compute_binary_hash(path: &Path) -> std::io::Result<String> {
    let data = std::fs::read(path)?;
    let mut hasher = Sha256::new();
    hasher.update(&data);
    Ok(hex::encode(hasher.finalize()))
}

fn truncate(s: &str, max: usize) -> String {
    if s.len() <= max { s.to_string() }
    else { format!("{}...", &s[..max]) }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::security::{Finding, ScanReport};
    use std::path::PathBuf;

    #[test]
    fn test_generate_report_clean() {
        let report = generate_report("test-project", &[], "Byte", 5, 10, 3, None);
        assert!(report.contains("# Security Compliance Report"));
        assert!(report.contains("test-project"));
        assert!(report.contains("CLEAN"));
        assert!(report.contains("Byte"));
    }

    #[test]
    fn test_generate_report_with_findings() {
        let scan = ScanReport {
            tool: "Semgrep".into(),
            target: PathBuf::from("/project"),
            findings: vec![Finding {
                tool: "Semgrep".into(),
                severity: Severity::Critical,
                rule_id: "sql-injection".into(),
                message: "SQL injection found".into(),
                file: PathBuf::from("app.py"),
                line: Some(42),
                owasp_category: Some("A03:2021".into()),
            }],
        };

        let report = generate_report("my-app", &[scan], "Shadow", 3, 5, 1, None);
        assert!(report.contains("HIGH"));
        assert!(report.contains("sql-injection"));
        assert!(report.contains("A03:2021"));
    }

    #[test]
    fn test_report_has_all_sections() {
        let report = generate_report("p", &[], "N", 1, 0, 0, None);
        assert!(report.contains("Executive Summary"));
        assert!(report.contains("SAST Results"));
        assert!(report.contains("SCA Results"));
        assert!(report.contains("Familiar Status"));
        assert!(report.contains("Binary Integrity"));
    }
}
